### ISSUE TITLE
run make test-agg fail

### ISSUE THREAD

**Issue by Unarimit** [scroll-tech/scroll-zkevm#147]
I read the code in `snark-verifier-cd02c9c9f799657f/a3d0a5a/snark-verifier-sdk/src/evm.rs:188:24` but have no idea what cause the failures.
```
[2023-06-02T02:51:42.502Z INFO  aggregation_tests] got super circuit proof
[2023-06-02T03:14:27.575Z INFO  aggregation_tests] finished aggregation generation
[2023-06-02T03:14:27.643Z INFO  aggregation_tests] finished byte code generation
test test_aggregation_api ... FAILED
failures:

---- test_aggregation_api stdout ----
Context "Range" used 33 advice columns and 17076467 total advice cells in phase 0
Special lookup advice cells: optimal columns: 0, total 0 cells used in phase 0.
Fixed columns: 1, Total fixed cells: 8031
Context "Range" used 33 advice columns and 17076467 total advice cells in phase 0
Special lookup advice cells: optimal columns: 6, total 2817792 cells used in phase 0.
Context "Range" used 1 advice columns and 12384 total advice cells in phase 1
Special lookup advice cells: optimal columns: 0, total 0 cells used in phase 1.
Fixed columns: 1, Total fixed cells: 8031
Context "Range" used 33 advice columns and 17076467 total advice cells in phase 0
Special lookup advice cells: optimal columns: 0, total 0 cells used in phase 0.
Fixed columns: 1, Total fixed cells: 8031
Context "Range" used 33 advice columns and 17076467 total advice cells in phase 0
Special lookup advice cells: optimal columns: 6, total 2817792 cells used in phase 0.
Context "Range" used 1 advice columns and 12384 total advice cells in phase 1
Special lookup advice cells: optimal columns: 0, total 0 cells used in phase 1.
Fixed columns: 1, Total fixed cells: 8031
Context "Range" used 33 advice columns and 17076467 total advice cells in phase 0
Special lookup advice cells: optimal columns: 0, total 0 cells used in phase 0.
Fixed columns: 1, Total fixed cells: 8031
Context "Range" used 33 advice columns and 17076467 total advice cells in phase 0
Special lookup advice cells: optimal columns: 6, total 2817792 cells used in phase 0.
Context "Range" used 1 advice columns and 12384 total advice cells in phase 1
Special lookup advice cells: optimal columns: 0, total 0 cells used in phase 1.
Fixed columns: 1, Total fixed cells: 8031
Context "Range" used 33 advice columns and 17076467 total advice cells in phase 0
Special lookup advice cells: optimal columns: 0, total 0 cells used in phase 0.
Fixed columns: 1, Total fixed cells: 8031
Context "Range" used 33 advice columns and 17076467 total advice cells in phase 0
Special lookup advice cells: optimal columns: 6, total 2817792 cells used in phase 0.
Context "Range" used 1 advice columns and 12384 total advice cells in phase 1
Special lookup advice cells: optimal columns: 0, total 0 cells used in phase 1.
Fixed columns: 1, Total fixed cells: 8031
computing length 206 fixed base msm
computing length 1723 MSM
computing length 206 fixed base msm
computing length 1723 MSM
computing length 206 fixed base msm
computing length 1723 MSM
thread 'test_aggregation_api' panicked at 'called `Option::unwrap()` on a `None` value', /home/dev/.cargo/git/checkouts/snark-verifier-cd02c9c9f799657f/a3d0a5a/snark-verifier-sdk/src/evm.rs:188:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/core/src/panicking.rs:111:5
   3: snark_verifier_sdk::evm::evm_verify
   4: zkevm::verifier::EvmVerifier::verify
   5: core::ops::function::FnOnce::call_once
   6: core::ops::function::FnOnce::call_once
             at /rustc/dfe3fe710181738a2cb3060c23ec5efb3c68ca09/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    test_aggregation_api

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5976.53s

error: test failed, to rerun pass `-p zkevm --test aggregation_tests`
```

**Comment by zhangdaozhu** [comment]
Which version are you using？

**Comment by Unarimit** [comment]
> Which version are you using？
latest main branch

**Comment by silathdiir** [comment]
Debugging on this issue. Found the output [RawCallResult](https://github.com/scroll-tech/snark-verifier/blob/halo2-ecc-snark-verifier-0323/snark-verifier/src/loader/evm/util/executor.rs#L733) with `exit_reason` as `OpcodeNotFound`:

```
RawCallResult {
    exit_reason: OpcodeNotFound,
    reverted: true,
    result: b"",
    gas_used: 18446744073709551615,
    gas_refunded: 0,
    logs: [],
    debug: None,
...
```

Seems caused by the updated `./tests/traces/erc20/erc20_10_transfer.json`, will debug with [revm](https://github.com/scroll-tech/snark-verifier/blob/halo2-ecc-snark-verifier-0323/snark-verifier/Cargo.toml#L29) in snark-verifier.

**Comment by silathdiir** [comment]
Hi @Unarimit, We could reproduce the issue you mentioned above.

It seems that it is caused by [solidity 0.8.20](https://github.com/ethereum/solidity/releases/tag/v0.8.20) which sets the default target EVM version to Shanghai including `PUSH0`.

We use [rvm 2.3.1](https://github.com/scroll-tech/snark-verifier/blob/halo2-ecc-snark-verifier-0323/snark-verifier/Cargo.toml#LL29C21-L29C26) in snark-verifer. It considers[PUSH0 95_u8](https://github.com/bluealloy/revm/blob/v19/crates/revm/src/instructions.rs#L85) as `OpcodeNotFound`.

I downgrade the solidity compiler and test (in progress). Could you check the version of your `solidity` compiler via `solc --version`?

**Comment by silathdiir** [comment]
`solidity 0.8.17` could work for me. You could install it via `svm-rs` as [snark-verifier CI](https://github.com/scroll-tech/snark-verifier/blob/2d5827de3acbcb4f1e2e1943fac8c88c068ebdf6/.github/workflows/ci.yaml#L27):
```
cargo install svm-rs
svm install 0.8.17
solc --version
```
<img width="855" alt="1" src="https://github.com/scroll-tech/scroll-zkevm/assets/31645658/3a91f9f1-c4fa-454a-9987-586456227c87">

**Comment by Unarimit** [comment]
My solidity compiler verision is `0.8.20` by `solc --version`. When I downgrade to `0.8.17` and rerun the command `run make test-agg`,  the test pass. Due to the issue was solved, I will close this stream. Thank you for your help @silathdiir .
